[config]
schemaVersion = "0.0.1"

[package]
namespace = "XoXFaby"
name = "BetterUI"
versionNumber = "2.0.0"
description = "Looking for translators! Various UI improvements like ordered items with multiple ways of sorting, DPSMeter, Item Counters, Skill/Equipment/Item Information, Command/Scrapper counters and other improvements, customizable StatsDisplay, and much more."
websiteUrl = "https://github.com/xoxfaby/BetterUI"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.19"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../zip"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "../bin/Release/netstandard2.0/BetterUI.dll"
target = "plugins/BetterUI/BetterUI.dll"

[[build.copy]]
source = "../bin/Release/netstandard2.0/publish/BetterUnityPlugin.dll"
target = "plugins/BetterUI/BetterUnityPlugin.dll"

[[build.copy]]
source = "../Languages"
target = "plugins/BetterUI/Languages"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["mods", "tweaks", "client-side"]
